export const data = [
        {
            type:"buy",
            size:200.0,
            price:"11.01"
        },     
        {
            type:"buy",
            size:303,
            price:"11.02"
        },
        {
            type:"buy",
            size:343,
            price:"11.03"
        },
        {
            type:"buy",
            size:306,
            price:"11.04"
        },
        {
            type:"buy",
            size:500,
            price:"11.05"
        },
        {
            type:"buy",
            size:456,
            price:"11.06"
        },
        {
            type:"buy",
            size:380,
            price:"11.07"
        },        {
            type:"buy",
            size:3300,
            price:"11.08"
        },
        {
            type:"ask",
            size:400,
            price:"11.11"
        },   
        {
            type:"ask",
            size:500,
            price:"11.12"
        },   
        {
            type:"ask",
            size:470,
            price:"11.13"
        },  
        {
            type:"ask",
            size:403,
            price:"11.14"
        },   
        {
            type:"ask",
            size:6200,
            price:"11.15"
        },   
        {
            type:"ask",
            size:1800,
            price:"11.16"
        },   
        {
            type:"ask",
            size:300,
            price:"11.17"
        },   
        {
            type:"ask",
            size:260,
            price:"11.18"
        },   
        {
            type:"ask",
            size:555,
            price:"11.19"
        },   
    ]

